name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ itslacchi@22}}" | docker login -u "${{ AMOGHAJOSHI }}" --password-stdin

    - name: Build Image
      run: docker build -t ${{ "AMOGHAJOSHI" }}/devops-app:latest .

    - name: Push Image
      run: docker push ${{AMOGHAJOSHI}}/devops-app:latest

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{AKIAZL3PR6KSFZNVXCP7}}
        aws-secret-access-key: ${{ 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}}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name devops-eks-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/
